const data = [
   {id:1 ,
    url:"/../public/design/lladro.JPG",
    heading:"LLadró",
    info:"Lladró, the Spanish porcelain company,  has been applying its unmatched expertise in porcelain for over 60 years. At the India Design Week, Lladró displayed its most innovative and cutting-edge porcelain, lighting, and timely classic masterpieces combining design with age-old craft techniques as an expression of emotion and diversity. The recently released Seasons Chandelier, Embraced by Jamie Hayon, the Fierce Portraits collection, the famed Origami Panther"},
   {id:2 ,
    url:"/../public/design/oorja.JPG",
    heading:"Oorja",
    info:"The concept behind Oorja is to transform trash and natural materials into beautiful lighting fixtures that also serve as a constant reminder of the essential need to build a more sustainable future. The company handcrafts lamps for retail usage and unique lighting solutions for projects and venues that are on commission. Founded by Jenny Pinto in 1998, Oorja creates beautiful and sustainable light sculptures while also ensuring waste minimization and promotion of eco-friendly practices"}, 
   {id:3 ,
    url:"/../public/design/indiaeyehome.JPG",
    heading:"Indie Eye Home",
    info:"Indie Eye Home is an initiative by Sunil Sethi Design Alliance which delves into creative designs for a variety of home decor projects. Their focus is on engaging with the varied interests of their clientele and curate products that suit their diverse individuality and eclecticism. All the designs are handcrafted in India and promote the vibrancy and multifaceted heterogeneity of contemporary India"},
   {id:4 ,
    url:"/../public/design/gharghar.JPG",
    heading:"Ghar Ghar",
    info:"Ghar Ghar Textile Company is a unique home décor company that is focused on making home styling fun and playful. The company takes inspiration from childhood memories of playing house or Ghar Ghar as it is known in India. The company understands that our homes should be a space where we can express ourselves and have fun, just like we did when we were kids "},
   {id:5 ,
    url:"/../public/design/hands.JPG",
    heading:"Hands",
    info:"Hands Carpets has a remarkable legacy spanning over 140 years, during which they have honed their craft to create some of the world's most exquisite and high-quality carpets with intricate and innovative designs. The company has become renowned for its ability to produce bespoke, handcrafted carpets that can be found in some of the most exclusive hotels, palaces, and residences around the world, cementing its position as a leader in the luxury carpet industry"},
   {id:6 ,
    url:"/../public/design/whitedomus.JPG",
    heading:"White Domus",
    info:"White Domus, a specialized art and design studio, was founded in 2016 by brothers Aroosh and Nitush Mahipal. They aim to revolutionize the use of stainless steel in interior design by incorporating modern art into everyday objects using cutting-edge technology and skilled craftsmanship. The brothers draw inspiration from nature's fundamental beauty and familiarity, which they breathe into metallic forms and embellish into larger-than-life sculptures"},
]

export default data;