const newseventsdata = [ 
   {id:'1' ,
    url:["/eventimages/galleryartpositiveBN/galleryartpositive (1).JPG","/eventimages/galleryartpositiveBN/galleryartpositive (2).JPG","/eventimages/galleryartpositiveBN/galleryartpositive (3).JPG","/eventimages/galleryartpositiveBN/galleryartpositive (4).JPG","/eventimages/galleryartpositiveBN/galleryartpositive (5).JPG","/eventimages/galleryartpositiveBN/galleryartpositive (6).JPG","/eventimages/galleryartpositiveBN/galleryartpositive (7).JPG","/eventimages/galleryartpositiveBN/galleryartpositive (8).JPG","/eventimages/galleryartpositiveBN/galleryartpositive (9).JPG"],
    heading:"Gallery Art Positive",
    info:["Be it about alienation or issues of resistance; radical criticism of the socio- political systems or playful irony and banter about the 'bhadralok', you find a rich diversity and multiplicity in the image-making emerging from the region. Landscapes and geographies dwell on memory as much as the flux in the present environment and the churn of both. 'Bengal-nama' pays tribute to artistic practitioners who approach a range of diverse subjects, from migration to geopolitics, mythology to ecology and a social critique of the present existential crisis with empathy and critical understanding. The artists bring alive through the terrestrial prism a glimpse of ideas and movements that are vitally relevant to our times, historically and politically from the past to now.","BAPI DAS | BAPPADITYA BISWAS | CHANDRA BHATTACHARJEE | DEBASISH MUKHERJEE | LALU PRASAD SHAW | JOGEN CHOWDHURY | K G SUBRAMANYAN | NARAYAN CHANDRA SINHA | NAJMUN NAHAR KEYA | PARITOSH SEN | PARTHA DASGUPTA | PROMOTHESH DAS PULAK | REBA HORE | SHAHRIA SHARMIN | SHIMUL SAHA | SHYAMAL DUTTA RAY | SOMA DAS | SOUMYA SANKAR BOSE | SUDIPTA DAS | YASMIN JAHAN NUPUR"],
    credit:"Hyperglot Review",
    category:"Art Events",
    subheading:"",},
    {id:'2' ,
    url:["/eventimages/blueprint.12/blueprint (1).JPG","/eventimages/blueprint.12/blueprint (2).JPG","/eventimages/blueprint.12/blueprint (3).JPG","/eventimages/blueprint.12/blueprint (4).JPG","/eventimages/blueprint.12/blueprint (5).JPG","/eventimages/blueprint.12/blueprint (6).JPG","/eventimages/blueprint.12/blueprint (7).JPG","/eventimages/blueprint.12/blueprint (8).JPG"],
    heading:"blueprint.12",
    info:["Zeenat Nagree writes “ Reimagining the meaning of being 'adrift at sea', Devika Sundar presents the internal expanse of the human body as aqueous forms that are unbound and untethered. In doing so, she brings out the uncanny echoes between us and bodies of water, in the way that they can be imaged, heard, and understood. This mode of enquiry emerged from Sundar's experiences with undiagnosed chronic pain and the research that led to on the differences between medical visualisations in the East and the West. Sundar found holistic representations that account for the body's ebbs and flows to provide better insight into the mysteries of its functioning in comparison with the fragmentation of the body into parts and symptoms as is standard in Western medicine. “ What remains central, nevertheless, to Sundar's practice is an acknowledgment of the enigmas of the human body and bodies of water that remain ambiguous and impenetrable.”"],
    credit:"Hyperglot Review",
    category:"Art Events",
    subheading:"",},
    {id:'3' ,
    url:["/eventimages/gallerienavya/gallerienavya (1).JPG","/eventimages/gallerienavya/gallerienavya (2).JPG","/eventimages/gallerienavya/gallerienavya (3).JPG","/eventimages/gallerienavya/gallerienavya (4).JPG","/eventimages/gallerienavya/gallerienavya (5).JPG","/eventimages/gallerienavya/gallerienavya (6).JPG","/eventimages/gallerienavya/gallerienavya (7).JPG","/eventimages/gallerienavya/gallerienavya (8).JPG"],
    heading:"Gallerie Nvya",
    info:["George Bataille introduced the notion of 'l'informe' - Formlessness. What Bataille means by Formlessness is that art should be brought down to earth, off of its pedestal where it has been standing since antiquity. For Bataille, creativity is in the process. The Formless, in a way, is abstract and indefinable - Bataille himself claims that a word has no definition. It is performative, rather than explanatory.In this exhibition, it is explored how these artists transcend from form to formlessness in their art. We also get to notice that each artist uses diverse mediums and techniques to define their expressions."],
    credit:"Hyperglot Review",
    category:"Art Events",
    subheading:"",},
    {id:'4' ,
    url:["/eventimages/vadheraartgallery/benodebehari/benodebehari (1).JPG","/eventimages/vadheraartgallery/benodebehari/benodebehari (2).JPG","/eventimages/vadheraartgallery/benodebehari/benodebehari (3).JPG","/eventimages/vadheraartgallery/benodebehari/benodebehari (4).JPG","/eventimages/vadheraartgallery/benodebehari/benodebehari (5).JPG"],
    heading:"Vadehra Art Gallery",
    info:["Through Wakefulness, A Night Rising presents a special body of work (from the early 1920s to the late 1950s) from across Mukherjee's travels and interests, including landscapes, figurations, flower studies, wood-cuts self-portraits as well as some post-blindness collages and compositions that create a memorable discourse around how vision appeared to him. Mukherjee's poignant reclamation of sight through intuition - replacing overt realism - suggests an unexpected but distinctive brand of late modernism in which individual perspective is prioritized through a vocabulary of motifs. Still, in some sense, the changing dichotomies of intimacy and distance that he explored in his practice were united in a kind of “indigenous modernism” through calligraphic techniques - and reveal his intention of maintaining an artistic and aesthetic approach even after he went blind, almost as if Mukherjee himself was preparing for total darkness in his search for the particularities of life through experience."],
    credit:"Hyperglot Review",
    category:"Art Events",
    subheading:"Benodebehari Mukherjee",},
    {id:'5' ,
    url:["/eventimages/vadheraartgallery/Treibor/Treibor (1).JPG","/eventimages/vadheraartgallery/Treibor/Treibor (2).JPG","/eventimages/vadheraartgallery/Treibor/Treibor (3).JPG","/eventimages/vadheraartgallery/Treibor/Treibor (4).JPG","/eventimages/vadheraartgallery/Treibor/Treibor (5).JPG"],
    heading:"Vadehra Art Gallery",
    info:["Once Around the Sun is a solo exhibition of Mawlong's wood-cuts and drawings that recognize the dignity of labor amidst the unevenness of development in contemporary reality alongside systemic issues like poverty, lack of education, inaccessibility to healthcare and infrastructure and a disconnection from the modern world in the Meghalayan village of Mawbri, situated in the remote district of Mawkyrwat. Inspired by forms of the graphic novel and comic books, Mawlong's wood-cuts are sequential stories that unfold in narrative time even within a flattened, often dramatic cropping. A jagged and persistent darkness glitches in his wood-cuts. Rampant though it is, the inky blackness of his mise-en-scène compositions is interrupted by slivers of white, a kind of anti-space that reforms the dynamics of negative and positive space, creating an eternal, spectral appearance. A source of light is self-generated perhaps from a screen, a tree or a caged chicken and travels through the composition with an enigmatic radiance that encourages a textual reading of his work, and often enough."],
    credit:"Hyperglot Review",
    category:"Art Events",
    subheading:"Treibor Mawlong",},
    {id:'6' ,
    url:["/eventimages/exhibit320/exhibit320 (1).JPG","/eventimages/exhibit320/exhibit320 (2).JPG","/eventimages/exhibit320/exhibit320 (3).JPG","/eventimages/exhibit320/exhibit320 (4).JPG","/eventimages/exhibit320/exhibit320 (5).JPG","/eventimages/exhibit320/exhibit320 (6).JPG","/eventimages/exhibit320/exhibit320 (7).JPG","/eventimages/exhibit320/exhibit320 (8).JPG","/eventimages/exhibit320/exhibit320 (9).JPG","/eventimages/exhibit320/exhibit320 (10).JPG"],
    heading:"Exhibit320",
    info:["Active as an artist, photographer, designer and filmmaker over a period of nearly six decades, Gopi Gajwani has always achieved his discoveries through the dissolution of the singular image. Whether he works in charcoal or acrylic, or employs pastel or Chinese ink, or renders his paintings in oils, or explores a combination of charcoal and watercolour, Gopi invites us to savour the electricity of the line that he teases into currents and stipples, into staccato rhythms and glissando sequences. He harvests fields of colour for us, which can be plangent or percussive, tranquil or flamboyant. He remains intensely aware of the prime question of legibility: How are his works to be read by those who receive them?","To this question, in ways subtle and elegant, the artist responds by pointing beyond language. Abstraction resists being relayed into words; it defies the expository and discursive procedures of interpretation. Instead, Gopi's paintings, drawings and mixed-media works act on our consciousness as music does: we are carried along by its patterns of tempo and cadence; we surrender before the effects of syncopation and riffing; the recurrence of beats and pauses builds into a graceful architecture of solace and surprise. We may plausibly regard these paintings as pieces of music, shaped through an interplay of compositional and improvisational energies."],
    credit:"Hyperglot Review",
    category:"Art Events",
    subheading:"Gopi Gajwani",},
    {id:'7' ,
    url:["/eventimages/khojstudios/khojstudios.JPG"],
    heading:"Khoj Studios",
    info:["Active as an artist, photographer, designer and filmmaker over a period of nearly six decades, Gopi Gajwani has always achieved his discoveries through the dissolution of the singular image. Whether he works in charcoal or acrylic, or employs pastel or Chinese ink, or renders his paintings in oils, or explores a combination of charcoal and watercolour, Gopi invites us to savour the electricity of the line that he teases into currents and stipples, into staccato rhythms and glissando sequences. He harvests fields of colour for us, which can be plangent or percussive, tranquil or flamboyant. He remains intensely aware of the prime question of legibility: How are his works to be read by those who receive them?","To this question, in ways subtle and elegant, the artist responds by pointing beyond language. Abstraction resists being relayed into words; it defies the expository and discursive procedures of interpretation. Instead, Gopi's paintings, drawings and mixed-media works act on our consciousness as music does: we are carried along by its patterns of tempo and cadence; we surrender before the effects of syncopation and riffing; the recurrence of beats and pauses builds into a graceful architecture of solace and surprise. We may plausibly regard these paintings as pieces of music, shaped through an interplay of compositional and improvisational energies."],
    credit:"Hyperglot Review",
    category:"Art Events",
    subheading:"",
  artists:[{id:'34',
  "heading":"Poornima Sukumar",
  url:["/eventimages/khojstudios/khoj1.JPG"],
  info:["Yesterday. Today. Everyday. collaborates and co-creates along with the people from the Transgender community to excavate the wisdom they have inculcated over the years. By diving deep into their culture and traditional practices, Poornima Sukumar in collaboration with Aravani Art Project, examines their spaces of innovation, the places of their history and creates new spaces by transforming this knowledge into art."],
  credit:"Hyperglot Review",
},{id:'35',
"heading":"Divya Chopra & Rwitee Mandal",
url:["/eventimages/khojstudios/khoj3.JPG"],
info:["Yesterday. Today. Everyday. collaborates and co-creates along with the people from the Transgender community to excavate the wisdom they have inculcated over the years. By diving deep into their culture and traditional practices, Poornima Sukumar in collaboration with Aravani Art Project, examines their spaces of innovation, the places of their history and creates new spaces by transforming this knowledge into art."],
credit:"Hyperglot Review",
},{id:'36',
"heading":"Sumedha Garg & Nitin Bathla",
url:["/eventimages/khojstudios/khoj4.JPG"],
info:["Otherworlds explores the complex & exploitative labour and class relationships in Kapashera - a tenement town that lies at the cusp of Delhi and Gurugram. It questions the meaning of home for people in a place that is in a perpetual state of flux and how the temporariness of livelihoods and belonging affects the lives of women in this space."],
credit:"Hyperglot Review",
},{id:'37',
"heading":"Shweta Bhattad",
url:["/eventimages/khojstudios/khoj5.JPG"],
info:["Cotton Stainers has created a space that is run by the women in Paradsinga, so that it becomes a platform of expression for their stories and concerns through sustainable clothing. Right from the sowing of cotton to spinning it into yarn, hand-weaving it into fabric and stitching it into garments, is all done by the women in this space"],
credit:"Hyperglot Review",
},{id:'38',
"heading":"Jasmeen Patheja",
url:["/eventimages/khojstudios/khoj6.JPG"],
info:["Towards Feminist Futures works with the vision to foster feminist solidarities to end gender-based violence and victim blame. The garment is a witness and memory of gender based injustice. It is present to say I Never Ask For It. #INeverAskForIt initiated by Blank Noise is a long-term mission to build ten thousand garment testimonials of sexual violence to end victim blame."],
credit:"Hyperglot Review",
},{id:'39',
"heading":"Swati Janu",
url:["/eventimages/khojstudios/khoj7.JPG"],
info:["'5 Bigha Zameen' aims to rethink our collective imaginations of the city and question whose rights are protected in our cities, and whose eroded. This project was carried out in collaboration with Social Design Collaborative."],
credit:"Hyperglot Review",
},{id:'40',
"heading":"Padmini Ray Murray",
url:["/eventimages/khojstudios/khoj8.JPG"],
info:["A Fever Dream of a Feminist Internet is a dream of an internet that privileges individual and community ownership and control, reconfigured through ethics of care. Padmini Ray Murray's project with Khoj is looking at how we are strangled by the tentacles of centralised internet infrastructures, both corporate and governmental, almost carceral in their increasingly suffocating demands on our data and diktats designed to manipulate our behaviour in online spaces."],
credit:"Hyperglot Review",
}
]
},
{id:'8' ,
url:["/eventimages/sumakshi/sumakshi.JPG"],
heading:"Afterlife",
info:["Singh's solo exhibition 'Afterlife' will feature ethereal thread drawings, installations, and animations of architectural fragments from her (now defunct) family home as they fracture and unravel into entropy. Sumakshi Singh is an artist and academic based in New Delhi, who also enjoys working as an academic. She has taught at the Art Institute of Chicago, Oxford University, and Columbia University among others. Recently, Sumakshi designed the renowned windows for Hermès, India. She has mentored residencies for The Victoria and Albert Museum, TheWhyNotPlace 2010 and 2011, and curated for the Devi Art Foundation. She is the recipient of several awards, including the Asia Arts Future Game Changer award by the Asia Society in 2022 ( to honor artists for their significant contributions to contemporary art), the YFLO award (from the Federation of Indian Chambers of Commerce & Industry) for achievement in the arts in 2019, a Zegna Grant in 2009, an Illinois Arts Council Award in 2007 (in recognition of outstanding work and commitment within the arts) and the Richard H. Driehaus Foundation Award in 2005 (to support and encourage excellence, artistry, focus, direction, maturity, and originality in the visual arts). Singh's installations open up a rich, silent space, which lies just before the world solidified by our perceptions. Our everyday 'given' are often questioned as her work begins to dissolve familiar forms and intimate memories into insubstantial mirages.","Afterlife - In her artistic oeuvre, Sumakshi Singh reconfigures the familiar axes of experience by engineering illusions through line and trace. The concrete constitution of architectural facades dissolves into textile ephemera, creating a mise-en-scene of spectral architectonics. Now uninhabitable, the facades offer themselves as experiential maps, harking back to the artist's palpable memories of her ancestral home on 33 Link Road, Delhi. Settled into by her deceased grandparents and standing for almost 70 years, the house no longer feels familiar to the artist like it did when it was still occupied. Singh started to look at the house and its constituent objects, corridors, and surfaces anew, and replicated them in her work with dimensional exactitude. Mounted to scale in the gallery, the house breathes through its simulation, attesting to an intense artistic need for perusal, absorption, and ultimately, surrender. The installations are created using thread of different kinds, levitating with wires to achieve the intended effect. Shadows are cast on the walls both naturally (against interior light sources) and through textile doubling, which further confounds vision. In contrast to Singh's installations in pre-Covid times, these works reveal a distinct sense of unravelling. Departing from the defined and measured contours of her earlier hand, Singh's concentrated experience of vulnerability, fear, and grieving during the pervasive malaise over the past two years percolated into her artistic sensibility. The threadwork on display then becomes, in Singh's words, a “transitional tapestry”, situated in the collisions of time, space, and memory. Through its recreations in embroidery, the house becomes a sentient archive. Memory is externalised and transferred to a material placeholder in thread, which activates the contours of a habitat on the brink of collapse. Scheduled to be sold or demolished in the near future, the house shifts anchors through Singh's work, reflecting her labour in processing a future past."],
credit:"Hyperglot Review",
category:"Art Events",
subheading:"",},
{id:'9' ,
url:["/eventimages/kochi/kochi1.JPG","/eventimages/kochi/kochi2.JPG","/eventimages/kochi/kochi3.JPG","/eventimages/kochi/kochi4.JPG","/eventimages/kochi/kochi5.JPG","/eventimages/kochi/kochi6.JPG"],
heading:"Kochi-Muziris Biennale",
info:["The Kochi-Muziris Biennale is an international exhibition of modern art that takes place in Kochi, Kerala, India. It is both the greatest contemporary art festival in Asia and the largest art exhibition in the nation. The Kerala State Government has supported the Kochi Biennale Foundation's proposal. Dr. Venu IAS, the culture secretary for the Keralan government, came up with the idea for the Kochi-Muziris Biennale and carried it out. The exhibition is spread out over Kochi, with performances taking place in already-existing galleries and halls and site-specific works in parks, historic buildings, and abandoned buildings. A variety of mediums are incorporated, including cinema, installation, painting, sculpture, new media, and performance art by Indian and international artists. The Kochi-Muziris Biennale seeks to invoke the latent cosmopolitan spirit of the modern metropolis of Kochi and its mythical past, Muziris, to create a platform that will introduce contemporary, global visual art theory and practice to India. It will attempt to showcase and debate new Indian and international aesthetics and experiences and enable a dialogue among artists, curators, cultural practitioners and the public."],
credit:"Hyperglot Review",
category:"Art Events",
subheading:"",},
{id:'10' ,
url:["/eventimages/galleryartandsoul/galleryartandsoul1.JPG"],
heading:"Gallery Art & Soul",
info:["Founded in 2003, Gallery Art & Soul is in the heart of Bombay presenting Indian modern and contemporary arts. The gallery was established by Dr. Tarana Khubchandani as an extension of her non-profit endeavours. The gallery has followed a worldwide and national discourse on aesthetic syncretism, producing exhibitions that are diverse in genre, materiality, and philosophical thought across art history.","Since its inception, Gallery Art & Soul has organised brilliant salon exhibitions and galas to assist breast cancer charities. Syed Haider Raza, Abdul Aziz Raiba, Krishna Reddy, Rabin Mondal, Lalitha Lajmi, Vasant Wankhede, Manu Parekh, Subhash Awchat, Vilas Shinde, Jinsook, Ankit Patel, Sujata Bajaj, Seema Kohli, Vinita Karim, Yashwant Deshmukh, and numerous more artists have had solo exhibitions and retrospectives there. The gallery has collaborated in hosting exhibitions with the National Gallery of Art, Mumbai, India Art Fair, India Habitat Center, CSMVS Museum, Mumbai, Jehangir Art Gallery, Sir JJ School of Art, Clark House Initiative, Kasturbhai Lalbhai Museum, India Art Festival, and The Royal Opera House."],
credit:"Hyperglot Review",
category:"Art Events",
subheading:"",
artists:[{id:'41',
"heading":"Mayuri Chari",
url:["/eventimages/galleryartandsoul/galleryartandsoul.JPG"],
info:["Mayuri Chari is a Goa-born artist who uses embroidery to record dialogues she has with her body about its existence in time and space. The female body is frequently a topic of discussion, control, criticism, and violence within India's patriarchal social system. According to colonial-era Victorian standards that have since been appropriated into a neo-fascist moral code that emphasises derivation from indigenous values drawn from old religious texts, public displays of nudity are discouraged. She mocks the hypocrisy of traditions which exclude women from their homes during their menstrual cycles because they are viewed as dirty while cow dung cakes are used as fuel and in religious ceremonies to purify oneself since it is deemed pure.","For millennia, Indian miniatures have consistently portrayed sensual forms and varied facets of nudity, especially when incorporated into the history and narrative of a nation or culture. She was rejected from a museum exhibition where the exclusion of a budding young artist was justified by the nudity in her works. Her stitched pieces in a different group show called Outsider praised the body of a woman who would have been the target of body shaming. The venue's proprietors urged her to take the piece down, but she chose to cover it with a black curtain that read, 'Don't open. I am Nude Inside.'"],
credit:"Hyperglot Review",
},{id:'42',
"heading":"Upendra Ram",
url:["/eventimages/galleryartandsoul/galleryartandsoul (1).JPG","/eventimages/galleryartandsoul/galleryartandsoul (2).JPG"],
info:["Upendra Ram portrays these childhood experiences in his works which have shaped his artistic expressions to a great extent. As a toddler, he would construct dolls out of clay from the town pond, much to his mother's dismay, who considered it as a feminine preoccupation. It was because of his uncle in Patna, who had witnessed the reverence for artists in the city with ancient roots and an enviable cultural heritage, that Ram's perception about his artform gradually underwent a transformation. When a string is tied to a dragonfly, it serves as a reminder of the desire to soar that most children in rural India share. He delves into the rituals and contradictions of rural faith and sacrifice by depicting a butchered pig and a weeping woman in his works.","Upendra Ram's unique addition to Indian ceramics is the illustrated tale, which deviates from the aesthetic and emphasises the need for function in the objects. Rather, it is sculptural, conceptual, and heavily influenced by form and narrative experimentation."],
credit:"Hyperglot Review",
}
]
},
{id:'11' ,
url:["/eventimages/chatterjeeandlal/chatterjeeandlal (3).JPG"],
heading:"Chatterjee & Lal",
info:["Mortimer Chatterjee and Tara Lal, a husband and wife duo, established Chatterjee & Lal in 2003. The gallery, which is now located in Mumbai's Colaba art district, is a prominent hub in the city's developing art scene. While the gallery has always placed a strong emphasis on the work of emerging artists, more recent programming has included historical content that expands our understanding of the histories of art and design in the twentieth century.","Artists in Focus: Arshi Irshad Ahmadzai, Minam Apang, Nikhil Chopra, Amshu Chukki, Shanti Dave, Naveen Kishore, Kausik Mukhopadhyay, Sahej Rahal, Nelly Sethna, Gagan Singh, Rustom Siodia, and Nityan Unnikrishnan."],
credit:"Chatterjee & Lal",
category:"Art Events",
subheading:"",
artists:[{id:'43',
"heading":"Shanti Dave",
url:["/eventimages/chatterjeeandlal/chatterjeeandlal (1).JPG"],
info:["Dave is renowned for both his paintings and his expansive murals, which are displayed in galleries and public areas all around the world. Some of his murals can be found in the VIP lounge at a New York airport as well as in the Air India offices in London, New York, Frankfurt, and Sydney. As may be observed from his use of formal abstraction, Dave was a modernist, unlike most other artists of his day. He places more of an emphasis on the medium and its potential than on incorporating ideological themes into his works. Later, he made a conscious decision to favour printmaking, drawn to the medium both for the broader democratic character it afforded both the artist and the client as well as for the potential for richer textures. Dave is renowned for his experiments using encaustic, in addition to oil, to produce high relief paintings."],
credit:"Chatterjee & Lal",
},{id:'44',
"heading":"Minam Apang",
url:["/eventimages/chatterjeeandlal/chatterjeeandlal (2).JPG"],
info:["Arunachal Pradesh-born visual artist Minam Apang. Her works have been displayed on numerous worldwide stages. In Mumbai, where she first started exhibiting her works at a gallery, she has had four solo exhibitions. She divides her time between sketching, farming, and music-making while residing in Goa and Arunachal Pradesh.Minam Apang uses ink and charcoal to create her abstract landscapes and allusions to regional folklore. Although the principal subjects of her early work were mythology and popular tales, she eventually developed an interest in the psychological reaction of familiarity and recognition to an image."],
credit:"Chatterjee & Lal",
},
{id:'45',
"heading":"Mayuri Chari",
url:["/eventimages/chatterjeeandlal/chatterjeeandlal (3).JPG"],
info:["His body of work is a developing narrative that uses mythical creatures and engages them in discourse with contemporary life. In these stories, these beings execute bizarre activities in abandoned areas of the city, transforming them into liminal ritual grounds. The temporal act and its aftermath are the main motifs in his work. My paintings are pages of a fragmented, quasi-historical manuscript that functions as an absurd encyclopedia of a fictional civilisation. The pages of this encyclopedia grow in the manner of Borges's The Book of Sand, with each page of the manuscript iteratively cataloguing the creatures that roam the civilisation, charting their origins, customs, rituals, and myths."],
credit:"Chatterjee & Lal",
},{id:'46',
"heading":"Upendra Ram",
url:["/eventimages/chatterjeeandlal/chatterjeeandlal (4).JPG"],
info:["Arshi has produced work that ranges in scale and medium and addresses a wide variety of issues. Arshi creates work that combines words and images in a way that at times may be reminiscent of fragments of ancient writings and at other times may be similar to deeply personal journals, all the while criticising the position, agency, and lack thereof, of the Muslim woman. In her project Lihaaf (2020), which was constructed by numerous women in her hometown of Najibabad as a huge quilt, Arshi discusses the verbal and emotional interactions that happen when women collaborate. Although her fundamental concerns and inquiries as an artist have, to a significant extent, stayed constant over the years, Arshi has handled her concerns from a variety of angles, each one unique to her position as a South Asian Muslim woman."],
credit:"Chatterjee & Lal",
}
]
},
{id:'12' ,
url:["/eventimages/iramart/iramart.JPG","/eventimages/iramart/iramart (1).JPG"],
heading:"Iram Art",
info:["Iram Art's core mission is to find and assist artists working in a variety of genres and media while also collaborating with established artists to build a strong and encouraging local and international community of artists and collectors. They are dedicated towards advancing contemporary art concepts and critical thinking in Ahmedabad, a city steeped in cultural history but without a significant contemporary art presence up to this point. Their goal is to establish a global benchmark, taking into account best practices and holistic programming to promote local rising talent as well as showcase Indian and international artists so that our community of artists, collectors, and art lovers have a place in their own city to study, discover, and collaborate.","Harsh Shah, the founder and visionary of Iram Art, was fascinated by art from a young age. He started working on art projects after earning his MBA in International Business and Finance from the USA. His goal propels Iram Art to success and, consequently, the progress of the artists they collaborate with. Harssh Shah is aware of the value of artists and the requirements of art collectors."],
credit:"Hyperglot Review",
category:"Art Events",
subheading:"",
artists:[{id:'47',
"heading":"Rakesh Patel",
url:["/eventimages/iramart/iramart (2).JPG","/eventimages/iramart/iramart (3).JPG"],
info:["Rakesh Patel has always been intrigued by art, particularly portraiture, but his more experimental mixed-media pieces were inspired by his family's business dealing in hardware and garbage. Patel's work today combines a variety of subjects and materials. A materialistic digital shared consciousness is symbolised through large-scale landscapes and kinetic installations. Using e-waste, Patel builds urban landscapes that are a reflection of the times we live in, a time when interpersonal connections are crucial but humanity has never been more disconnected."],
credit:"Hyperglot Review",
},{id:'48',
"heading":"Narayan Sinha",
url:["/eventimages/iramart/iramart (4).JPG","/eventimages/iramart/iramart (5).JPG"],
info:["Narayan Sinha was more connected to nature as a result of his rural upbringing. Raw materials are a recurring theme in all of his works, which are all odes to the fundamental elements of the environment in which he found himself. He had dreams of recreating existence through mechanical means after spending a lot of time around the nearby automobile industry. This thin line separating life from inanimate items keeps driving him to look beyond simplistic interpretations and investigate what it means to be present as an individual at this moment in time and experience life through multiple perspectives."],
credit:"Hyperglot Review",
},
]
},
{id:'13' ,
url:["/eventimages/gallerydotwalk/gallerydotwalk (1).JPG"],
heading:"Gallery Dotwalk",
info:["Dotwalk is dedicated to creating a venue for art that is centred on authenticity and integrity, that attracts up-and-coming artists, that communicates with art lovers around the world via technology, and that enhances the art world. Sreejith CN, a prominent figure in the Indian art scene for the past 20 years, is a promoter of Gallery Dotwalk. Dotwalk debuted its main gallery in Gurugram, Delhi-National Capital Region, in April 2022 with the exhibition 'An unlocated window of myself.' Aman Khanna, Arjun Das, Chandrashekar Koteshwar, Chetnaa, Gigi Scaria, Himani Gupta, GR Iranna, Jagannath Panda, Manisha Gera Baswani, Pooja Iranna, Prerna Sharma, Ravinder Reddy, Sujith SN, and Sumedh Rajendran were among the 14 artists featured in the Premjish Achari-curated exhibition.",""],
credit:"Hyperglot Review",
category:"Art Events",
subheading:"",
artists:[{id:'49',
"heading":"Chandrashekar Koteshwar",
url:["/eventimages/gallerydotwalk/gallerydotwalk (2).JPG"],
info:["Chandrashekar has advanced to a more complex and difficult search into objecthood itself through his current body of work. Most of the time, he intentionally sets his creations to be incongruent. The purpose is to challenge the way forms and images are put together, as well as the meaning-making process itself, as incomplete meanings can never be fully understood. Chandrashekar draws inspiration from historical figures and conventional sculptural and cultural artefacts and he constructs his own versions without much regard for the rules and canons of tradition."],
credit:"Hyperglot Review",
},{id:'50',
"heading":"Manas Naskar",
url:["/eventimages/gallerydotwalk/gallerydotwalk (4).JPG"],
info:["In order to better comprehend the changes in nature and the environment in his immediate surroundings, Manas Naskar experiments with different painting materials and techniques. He is attempting to revisit the current genre of paintings in a way that more closely resembles the romantics' ideology, which views both the calmness and the wrath of nature as beautiful. Manas strives to catch those ephemeral moments when a minute shift in the position of the sun produces a wonderful aura."],
credit:"Hyperglot Review",
},{id:'51',
"heading":"Midhun Gopi",
url:["/eventimages/gallerydotwalk/gallerydotwalk (5).JPG"],
info:["The journeys shown in Midhun's paintings seem to never end; they take the viewer through the wilderness, the cosmos, the interior landscapes of the mind, and the hardships of society. In certain instances, he weaves memories and feelings together so that they are lucid yet possess complexity. In his works, the sceneries and forms blend together and start to complement one another. The images evoke a sense of individual or community recollection mingled with forms."],
credit:"Hyperglot Review",
},{id:'52',
"heading":"Prerna Sharma",
url:["/eventimages/gallerydotwalk/gallerydotwalk (6).JPG"],
info:["Prerna uses fish as a metaphor for the psychological conflicts and feelings that people experience when they deal with others and with themselves. She believes that given that we can't see or hear a fish's agony or fear while they experience a range of emotions, suffering is frequently concealed on a person's face. The fish have tear ducts, but since their eyes are constantly wet, we cannot see them cry. Prerna still vividly recalls images of mass graves of dead people from the horrific tsunami that struck the coastline in 2014. Additionally, she utilises the analogy of fish to describe the trauma."],
credit:"Hyperglot Review",
},{id:'53',
"heading":"Sneh Mehra",
url:["/eventimages/gallerydotwalk/gallerydotwalk (7).JPG"],
info:["The works of Sneh Mehra are largely concerned with the land and environment and include other multidisciplinary aspects such as the evolution of the land, the environment and ecology, climate change, animal behaviour, etc. These are all staged in the landscape regime, which, throughout the history of art, has only ever been used to show natural surroundings such as mountains, rivers, sky, seascapes, etc. as the background of portraits. Her art is inspired by references that reflect her surroundings and the shards of chaotic growth and disintegration."],
credit:"Hyperglot Review",
},{id:'54',
"heading":"Tanaya Rao Raj",
url:["/eventimages/gallerydotwalk/gallerydotwalk (1).JPG"],
info:["Tanaya is passionate about upcycling and incorporates discarded and salvaged materials into her art practice. Her creations are the outward expressions of an innate need and need to employ (or repurpose) all manner of trash, including found things and materials. She uses paint and katran (or textile waste) to create varied sceneries and/or abstract forms that are influenced by nature in her most recent body of work. She considers every type of discarded material to be a reflection of herself, aiming to give each piece of art a unique purpose and identity."],
credit:"Hyperglot Review",
},
]
},{id:'14' ,
url:["/eventimages/galleryganesha/galleryganesha (2).JPG","/eventimages/galleryganesha/galleryganesha (1).JPG","/eventimages/galleryganesha/galleryganesha (3).JPG","/eventimages/galleryganesha/galleryganesha (4).JPG","/eventimages/galleryganesha/galleryganesha (5).JPG","/eventimages/galleryganesha/galleryganesha (6).JPG"],
heading:"Gallerie Ganesha",
info:["Gallerie Ganesha has successfully promoted two young artists, Paresh Maity and Neeraj Goswami, who are now regarded as artists of note on a national level. There have been numerous others, including, but not limited to, Jayasri Burman, Sisir Sahana, Mohan Singh, and Devdatta Padekar. In earlier years, Shobha Bhatia, director and founder of Gallerie Ganesha, was successful in raising the necessary awareness by offering a gallery environment that was friendly rather than intimidating. The gallery serves as a platform and gathering place for both artists and art enthusiasts and the idea that art should both please the eye and the heart is one that Gallerie Ganesha still adheres to.","Artists in Focus: IAF 2023 - A Ramachandran, Ajoy Ghosh, Bimal Dasgupta, Biren De, Dhirendranath Brahma, Gopal Ghose, M B Gupta, M K Parandekar, Maniklal Banerji, P A Dhond, Paresh Maity, Prankrishna Pal, Ramananda Bandyopadhyay, Ramkinkar Baij, Sakti Burman, Shyamal Datta Ray, and Prof. K. S. Kulkarni.","Master Watercolourists - Since the mid-thirties, watercolour has been mostly overshadowed by the expanding power of the oil medium for about four decades. Anathema to the purist school of the watercolour medium, the clean transparency of watercolours were frequently combined with the application of gouache or body colour in the majority of urban art centres in India. The medium nevertheless kept the incredible tonal richness that Abanindranath Tagore, Gaganendranath Tagore, and Nandlal Bose had given it when they incorporated the technique that had been developed from the conventional Sino-Japanese customs.","Prof. K.S.Kulkarni - Prof. K.S.Kulkarni was one of the founders of the Triveni Kala Sangam in addition to being a teacher. He also rose to the position of founding president of Delhi Shilpi Chakra, an organisation of artists founded in 1949 to support and uplift young progressive minds in the Delhi region. At this point, Kulkarni became known for his kindness as a teacher, an artist, and a leader in the establishment of institutions. From 1969 to 1972, he served as a visiting lecturer at Skidmore College in New York. He was selected by the Indian government as a National Emeritus Professor in 1984 for his great contributions to art. In 1985, the Sahitya Kala Parishad gave him the Parishad Samman."],
credit:"Hyperglot Review",
category:"Art Events",
subheading:"",
},{id:'15' ,
url:["/eventimages/dhiartspace/dhiartspace (1).JPG","/eventimages/dhiartspace/dhiartspace (2).JPG"],
heading:"Dhi Artspace",
info:["Bhargavi Gundala founded the Hyderabad-based Dhi Artspace in 2014. She is an artist as well as a patron and collector of modern art and encourages emerging artists by providing a forum for dialogue and engagement. Since its debut, Dhi has collaborated with new and up-and-coming contemporary artists and has sparked numerous discussions on Indian art practices. Dhi Collective, an intervention outside the white cube space that serves as an incubator for debates, is the result of the gallery's efforts to stimulate creative and intercultural expression. Dhi hosts its annual artist residency as well as workshops, seminars, and mentorship programmes throughout the year. It is connected to a network of artists, curators, scholars, and art fans.","This year, Dhi Artspace is showcasing the works of four emerging contemporary artists whose inspiration comes from the discipline of visual storytelling. While Leena Raj chooses to translate popular proverbs from Malayalam onto her canvases, Poorvesh Patel uses rusted copper wires as a medium to revisit his early memories of farming in Gujarat, and Sumana Som stitches pieces of her personal history and life together in one plane. Arjun Das iterates the story of workers in Kolkata's Bara Bazar in his compositions. The artists use a variety of media while reflecting on their socio-cultural identities to start discussions about urbanisation, migration, labour, and the environment.","Arjun Das - Arjun recounts the struggles of the immigrant working class in Kolkata and makes mention of the lives of young labourers who were forced to forgo their elementary education in order to start over in the city, an 'imagined' paradise. He reacts to the interiority of a displaced laborer's daily existence using a wide range of dialogues with the workers in Bara Bazar, Kolkata, together with his experiences as a young immigrant in the city. In his most recent works, Arjun expands on his earlier explorations of wood to include fresh inquiries into metal, stone, coal, terracotta roof tiles, and asphalt—all essential components of the city worker's daily life.","Leena Raj - Leena views the typical conception of a home as a constrained area of homogenised identities and broadens the idea of a person's home beyond the defined space of four walls. According to her, a home is made up of diverse lives brought about by the affectionate companionship or the incongruities of unfamiliarity in the relationships of its other residents. She searches for a place to call home in all directions and, as she shows her fondness for diverse microcosms, creates fantastical landscapes in which people coexist peacefully with the natural world.","Poorvesh Patel - Poorvesh's colour scheme serves as the protagonist in his works, which are amplified accounts of his personal adventures. Through his works, his emotional behaviour interacts with the current socio-political environment. He uses examples from his everyday life to help create a mental image, and compares it to his subconscious. That idea is omnipresent in his workflow. “It is like seeing another life after a loss. It is like the phoenix having a rebirth every time.”","Sumana Som - Sumona engages in the practice of cartography, examining the aesthetics of visual representation while incorporating elements from Indian miniature painting traditions into her creations. She primarily uses textiles and manipulates the spatial relationships between her subjects to build layered narratives that unite the past and present in a single frame. Sumana addresses the intricate relationships between distance, boundary, ownership, encroachment, and power structures that permeate our daily lives through her endeavour."],
credit:"Hyperglot Review",
category:"Art Events",
subheading:"",
},{id:'16' ,
url:["/eventimages/banglorelitfest/banglorelitfest (1).JPG","/eventimages/banglorelitfest/banglorelitfest (2).JPG","/eventimages/banglorelitfest/banglorelitfest (3).JPG","/eventimages/banglorelitfest/banglorelitfest (4).JPG","/eventimages/banglorelitfest/banglorelitfest (5).JPG","/eventimages/banglorelitfest/banglorelitfest (6).JPG","/eventimages/banglorelitfest/banglorelitfest (7).JPG","/eventimages/banglorelitfest/banglorelitfest (8).JPG","/eventimages/banglorelitfest/banglorelitfest (9).JPG","/eventimages/banglorelitfest/banglorelitfest (10).JPG","/eventimages/banglorelitfest/banglorelitfest (11).JPG"],
heading:"Bangalore literature Festival",
info:["Beautiful gardens and parks, the gulmohar in full bloom, the most salubrious weather - Bengaluru has always inspired creative thinkers and authors. The Bangalore Literature Festival celebrates this creative spirit of the city popular as the Garden City of India and commemorates the literary diversity it offers, bringing it in conversation with the best minds in the world of literature within and outside India."],
credit:"Hyperglot Review",
category:"Literary Events",
subheading:"",
},{id:'17' ,
url:["/eventimages/muskanlitfest/Muskaan1.JPG","/eventimages/muskanlitfest/Muskaan3.JPG","/eventimages/muskanlitfest/Muskaan4.JPG"],
heading:"Muskaan Literature Festival",
info:["The first ever children's literature festival, 'Muskaan Literature Festival for Child authors' has been organised by Prabha Khaitan Foundation which inaugurated on 10th of January. The festival is supported by Shree Cement and is being held in collaboration with Indira Gandhi National Centre for the Arts, with Sahitya Akademi as knowledge partner."],
credit:"Hyperglot Review",
category:"Literary Events",
subheading:"",
},{id:'18' ,
url:["/eventimages/jaipurlitfest/jaipurlitfest (1).JPG","/eventimages/jaipurlitfest/jaipurlitfest (2).JPG","/eventimages/jaipurlitfest/jaipurlitfest (4).JPG"],
heading:"Jaipur Literature Festival",
info:["Described as the 'greatest literary show on Earth', the Jaipur Literature Festival is a sumptuous feast of ideas.The past decade has seen it transform into a global literary phenomenon having hosted nearly 2000 speakers and welcoming over a million book lovers from across India and the globe. Over the past 15 years, our core values remain unchanged: to serve as a democratic platform offering access to all.","Every year, the Festival brings together a diverse mix of the world's greatest writers, thinkers, humanitarians, politicians, business leaders, sports people and entertainers on one stage to champion the freedom to express and engage in thoughtful debate and dialogue. Writers and Festival Directors Namita Gokhale and William Dalrymple, alongside producer Teamwork Arts, invite speakers to take part in the five-day programme set in the historic and dynamic state capital Jaipur. Past speakers have ranged from Nobel Laureates J.M. Coetzee, Orhan Pamuk and Muhammad Yunus, Man Booker Prize winners Ben Okri, Margaret Atwood and Paul Beatty, Sahitya Akademi winners Girish Karnad, Gulzar, Javed Akhtar, M.T. Vasudevan Nair as well as the late Mahasweta Devi and U.R. Ananthamurthy along with literary superstars including Amish Tripathi, Chimamanda Ngozi Adichie and Vikram Seth.","An annual event that goes beyond literature, the Festival has also hosted Amartya Sen, Amitabh Bachchan, the late A.P.J. Abdul Kalam, His Holiness the 14th Dalai Lama, Oprah Winfrey, Stephen Fry, Thomas Piketty and former president of Afghanistan, Hamid Karzai."],
credit:"Hyperglot Review",
category:"Literary Events",
subheading:"",
},{id:'19' ,
url:["/eventimages/kolkatalitmeet/kolkatalitmeet (1).JPG","/eventimages/kolkatalitmeet/kolkatalitmeet (2).JPG","/eventimages/kolkatalitmeet/kolkatalitmeet (4).JPG"],
heading:"Kolkata Literary Meet",
info:["The Kolkata Literary Meet - or Kalam, which is their preferred daaknaam - was overwhelmingly well-received when it debuted at the Kolkata Book Fair in January 2012. Their aim is to present writers from all over the globe, writers of as many different genres as possible, alongside speakers representing India. With topics as varied as history, sport, geopolitics and cinema. No registrations, no passes, no tickets. Just turn up, participate in the discussions, get involved in the debates and enjoy the tales from some of the greatest storytellers of our times. Kolkata Literary Meet is a meet that caters to the readers."],
credit:"Hyperglot Review",
category:"Literary Events",
subheading:"",
},{id:'20' ,
url:["/eventimages/keralalitfest/keralalitfest (1).JPG","/eventimages/keralalitfest/keralalitfest (2).JPG","/eventimages/keralalitfest/keralalitfest (4).JPG","/eventimages/keralalitfest/keralalitfest (4).JPG","/eventimages/keralalitfest/keralalitfest (5).JPG","/eventimages/keralalitfest/keralalitfest (6).JPG"],
heading:"Kerala Literature Festival",
info:["A premier literary festival of India held annually on the beaches of Calicut. KLF is a non-aligned platform, committed to providing an open and liberal forums for debates and discussion to foster progressive discourses. KLF brings writers, thinkers and activists closer, to people of varied backgrounds and interests and empower writers, thinkers to take the liberty to exercise freedom of thought and expression.Touted as the “grandest celebration of words, ideas, and stories”, the Kerala Literature Festival has swiftly become one of the largest cultural gatherings in Asia and the largest in South India.","Every year, KLF hosts Nobel Laureates, Oscar winners, Booker Prize recipients and other literary luminaries.The sessions at KLF, aim to map literaturEthrough discussions on aspects of History & Politics, Economics,Science, Art, Cinema & Culture, Technology, Genomics, Environment, Business and Health among other areas."],
credit:"Hyperglot Review",
category:"Literary Events",
subheading:"",
},{id:'21' ,
url:["/eventimages/ChappaiChhabi/ChappaiChhabi1.JPEG","/eventimages/ChappaiChhabi/ChappaiChhabi2.JPEG","/eventimages/ChappaiChhabi/ChappaiChhabi3.JPEG"],
heading:"Chappai Chhabi Vol. 2 - Book Launch",
info:["Day 2 of the Interfaces exhibition was marked by the launch of the book 'Chappai Chhabi Vol. 2' and a poetry reading session. The event took place on the 24th of June at M. L. Bhartiya Auditorium, in the presence of renowned poets and guests. The book 'Chappai Chhabi Vol. 2' is a publication supported by the Lalit Kala Akademi, New Delhi. It is the brainchild of Monali Roy and Moumita Mitra, who are part of INFUSED STORY, a multidimensional cultural group based in Delhi/NCR. INFUSED STORY aims to go beyond boundaries by merging words with various art forms such as poetry, dance, and drama. Monali Roy, the author, has previously written and published several books, including the anthology 'Chappai Chhabi Vol. 1' and 'Jiro Brij: Ami o Shoonya,' which beautifully blend art and poetry in a trilingual form.","The event witnessed the participation of esteemed poets like Agni Roy, Taslima Nasrin, Gautam Dasgupta, and Yashodhara Ray Chowdhury, among others. Additionally, celebrated poets including Dilip Fouzdar, Pran G Basak, Sarthak Roy Chowdhury, Mitul Dutta, Prashanta Barik, Sampa Banerjee, Shibu Mandal, Pijush Biswas, Debalina Bhattacharjee, Sonali Mitra, Moumita Mitra, Prasenjit Dasgupta, and Monali Roy were also in attendance.","The exhibition was held at Gallerie Romain Rolland, Alliance Française de Delhi, Lodhi Road, New Delhi. It encompassed the exploration and celebration of the inclusive and multifaceted nature of art. The exhibition spanned from June 23rd to July 3rd, offering visitors a chance to engage with various forms of art, including visual art, design, and the rich cultural heritage of India. Through the collaboration between the Embassy of Belgium, World University of Design, and Lalit Kala Akademi, the event aimed to promote the diversity of artistic expressions and foster meaningful interactions between artists, art enthusiasts, and the general public. Day 2 of the exhibition, with the book release and poetry reading session, added another layer of artistic depth and appreciation to the overall experience. It allowed visitors to delve into the world of poetry and witness the intersection of literature and visual art, creating a truly immersive and engaging cultural event."],
credit:"Hyperglot Review",
category:"Literary Events",
subheading:"",
},{id:'22' ,
url:["/eventimages/IICevent/IICevent (1).JPG","/eventimages/IICevent/IICevent (2).JPG","/eventimages/IICevent/IICevent (3).JPG","/eventimages/IICevent/IICevent (4).JPG"],
heading:"A Book discussion - India's Finance Ministers :",
info:["On July 4th, 2023, a book discussion group event took place at the India International Centre, centered around the recently published book by A.K. Bhattacharya titled 'India's Finance Ministers: From Independence to Emergency (1947-1977)'. The book, published by Penguin Business, delves into the lives and contributions of India's finance ministers during the crucial period of 1947 to 1977. The event brought together an esteemed panel of speakers, including renowned individuals from the economic and policy domains.","Among the notable speakers were Dr. Shankar N. Acharya, former Chief Economic Adviser of the Government of India; Dr. Montek Singh Ahluwalia, a Distinguished Fellow at the Centre for Social and Economic Progress and former Deputy Chairman of the Planning Commission; Dr. Nitin Desai, a former Chief Economic Adviser of the Government of India; Dr. V. Anantha Nageswaran, the Chief Economic Adviser of the Government of India; Shri Mohit Gupta, the founder of Frob, who acted as the moderator, and Shri A. K. Bhattacharya himself, the Editorial Director of Business Standard and the author of the book.","'From Independence to Emergency: India's Finance Ministers 1947-1977' provides a captivating account of the finance ministers who played pivotal roles in shaping India's economy during its formative years after independence. The book highlights their immense influence on economic management and government policy, leaving an indelible mark on the minds of Indian citizens.","The event at the India International Centre served as a platform to discuss and celebrate the insights and contributions made by these finance ministers, shedding light on their unique perspectives and the lasting impact they had on India's economic trajectory. It was an opportunity for the audience to engage with the author and the esteemed speakers, gaining a deeper understanding of India's economic history and the individuals who shaped it."],
credit:"Hyperglot Review",
category:"Literary Events",
subheading:"From Independence to Emergency(1947-1977)",
},
{id:'23' ,
url:["/eventimages/linesofflight/linesofflight.jpeg"],
heading:"Lines of Flight",
info:["Hyperglot Review presented the captivating poetry reading event “Lines of Flight” during our remarkable art exhibition REDRAWING ARTSCAPES. Poetry, akin to visual arts and music, possesses an innate ability to transcend boundaries and evade rigid definitions. It is a dynamic “line of flight” that encompasses not only escape and elusion but also fluidity, leakage, and gradual dissolution into the vast expanse. The featured poets included Bhaswati Goswami, Jayshree Misra Tripathi, Seema Jain, and Trina Chakraborti.","The event took place on Sunday, 27th August 2023, at CSOI in Chanakyapuri, New Delhi. For inquiries, please reach out via phone at +91-97171 89650/659 or email at info@hyperglotreview.com. You can also visit our website at www.hyperglotreview.com. Join us on this poetic journey where language takes flight and transcends boundaries!"],
credit:"Hyperglot Review",
category:"Literary Events",
subheading:"",
},{id:'24' ,
url:["/eventimages/thetwovoices/thetwovoices.jpeg"],
heading:"The Two Voices",
info:["Hyperglot Review presented the captivating poetry reading event “The Two Voices” during our remarkable art exhibition REDRAWING ARTSCAPES. Poetry, akin to visual arts and music, possesses an innate ability to transcend boundaries and evade rigid definitions. It is a dynamic “line of flight” that encompasses not only escape and elusion but also fluidity, leakage, and gradual dissolution into the vast expanse. The featured poets included Bhaswati Goswami, Jayshree Misra Tripathi, Rahul Gaur, and the discussion was moderated by Dominic Biswas.","The event took place on Sunday, 27th August 2023, at CSOI in Chanakyapuri, New Delhi. For inquiries, please reach out via phone at +91-97171 89650/659 or email at info@hyperglotreview.com. You can also visit our website at www.hyperglotreview.com. Join us in this literary exploration where voices converge and perspectives unite!"],
credit:"Hyperglot Review",
category:"Literary Events",
subheading:"",
},{id:'25' ,
url:["/eventimages/Delhicomiccon2023/Delhicomiccon2023.jpeg"],
heading:"Delhi Comic Con 2023",
info:["Delhi Comic Con 2023 was a dream come true for fans of comics, manga, anime, and all things geeky. The event, in collaboration with Crunchyroll, the world's leading anime streaming platform, unfolded its vibrant celebration from December 8 to 10, 2023, at NSIC Exhibition Ground Okhla, Delhi. The convention emerged as a colossal success, drawing in a staggering 46,000 attendees over the three action-packed days. The visitors were treated to a plethora of attractions, such as exclusive merchandise, gaming zones, live performances, workshops, panel discussions, and meet-and-greet sessions with celebrities and artists from the industry.","But the highlight of the event was undoubtedly the cosplay contest, which turned the convention into a spectacle of creativity and passion. Nearly 5,000 cosplayers participated in the contest, bringing to life characters ranging from anime icons like Naruto and Pokemon to timeless classics like Deadpool and Joker. The cosplayers impressed the judges and the audience with their costumes, props, makeup, and performance, and competed for the coveted prizes and titles. The ever-growing love for characters such as Hisoka, Halo, Sasuki, and the myriad Spiderman variations showcased the diversity and dynamism within the fandom.","Delhi Comic Con 2023 was a memorable experience for everyone who attended, and a testament to the power and popularity of comics, manga, and anime in India. The event was a celebration of the art, culture, and community that these mediums have created and inspired. It was also a platform for the fans to express themselves, connect with each other, and have fun. Delhi Comic Con 2023 was truly an alchemy of perception, transforming the ordinary into the extraordinary."],
credit:"Hyperglot Review",
category:"Literary Events",
subheading:"",
},
{id:'26' ,
url:["/eventimages/galleryganesha/galleryganesha (1).JPG","/eventimages/galleryganesha/galleryganesha (2).JPG","/eventimages/galleryganesha/galleryganesha (3).JPG","/eventimages/galleryganesha/galleryganesha (4).JPG","/eventimages/galleryganesha/galleryganesha (5).JPG","/eventimages/galleryganesha/galleryganesha (6).JPG"],
heading:"Gallerie Ganesha",
info:["Gallerie Ganesha has successfully promoted two young artists, Paresh Maity and Neeraj Goswami, who are now regarded as artists of note on a national level. There have been numerous others, including, but not limited to, Jayasri Burman, Sisir Sahana, Mohan Singh, and Devdatta Padekar. In earlier years, Shobha Bhatia, director and founder of Gallerie Ganesha, was successful in raising the necessary awareness by offering a gallery environment that was friendly rather than intimidating. The gallery serves as a platform and gathering place for both artists and art enthusiasts and the idea that art should both please the eye and the heart is one that Gallerie Ganesha still adheres to.","Prof. K.S.Kulkarni was one of the founders of the Triveni Kala Sangam in addition to being a teacher. He also rose to the position of founding president of Delhi Shilpi Chakra, an organisation of artists founded in 1949 to support and uplift young progressive minds in the Delhi region. At this point, Kulkarni became known for his kindness as a teacher, an artist, and a leader in the establishment of institutions. From 1969 to 1972, he served as a visiting lecturer at Skidmore College in New York. He was selected by the Indian government as a National Emeritus Professor in 1984 for his great contributions to art. In 1985, the Sahitya Kala Parishad gave him the Parishad Samman.","Artists in Focus: IAF 2023: A Ramachandran, Ajoy Ghosh, Bimal Dasgupta, Biren De, Dhirendranath Brahma, Gopal Ghose, M B Gupta, M K Parandekar, Maniklal Banerji, P A Dhond, Paresh Maity, Prankrishna Pal, Ramananda Bandyopadhyay, Ramkinkar Baij, Sakti Burman, Shyamal Datta Ray, and Prof. K. S. Kulkarni.","Master Watercolourists: Since the mid-thirties, watercolour has been mostly overshadowed by the expanding power of the oil medium for about four decades. Anathema to the purist school of the watercolour medium, the clean transparency of watercolours were frequently combined with the application of gouache or body colour in the majority of urban art centres in India. The medium nevertheless kept the incredible tonal richness that Abanindranath Tagore, Gaganendranath Tagore, and Nandlal Bose had given it when they incorporated the technique that had been developed from the conventional Sino-Japanese customs.",""],
credit:"Hyperglot Review",
category:"Art Events",
subheading:"",
},
{id:'27' ,
url:["/eventimages/dhiartspace/dhiartspace (1).JPG","/eventimages/dhiartspace/dhiartspace (2).JPG"],
heading:"Dhi Artspace",
info:["Bhargavi Gundala founded the Hyderabad-based Dhi Artspace in 2014. She is an artist as well as a patron and collector of modern art and encourages emerging artists by providing a forum for dialogue and engagement. Since its debut, Dhi has collaborated with new and up-and-coming contemporary artists and has sparked numerous discussions on Indian art practices. Dhi Collective, an intervention outside the white cube space that serves as an incubator for debates, is the result of the gallery's efforts to stimulate creative and intercultural expression. Dhi hosts its annual artist residency as well as workshops, seminars, and mentorship programmes throughout the year. It is connected to a network of artists, curators, scholars, and art fans.","This year, Dhi Artspace is showcasing the works of four emerging contemporary artists whose inspiration comes from the discipline of visual storytelling. While Leena Raj chooses to translate popular proverbs from Malayalam onto her canvases, Poorvesh Patel uses rusted copper wires as a medium to revisit his early memories of farming in Gujarat, and Sumana Som stitches pieces of her personal history and life together in one plane. Arjun Das iterates the story of workers in Kolkata's Bara Bazar in his compositions. The artists use a variety of media while reflecting on their socio-cultural identities to start discussions about urbanisation, migration, labour, and the environment.","Arjun Das: Arjun recounts the struggles of the immigrant working class in Kolkata and makes mention of the lives of young labourers who were forced to forgo their elementary education in order to start over in the city, an 'imagined' paradise. He reacts to the interiority of a displaced laborer's daily existence using a wide range of dialogues with the workers in Bara Bazar, Kolkata, together with his experiences as a young immigrant in the city. In his most recent works, Arjun expands on his earlier explorations of wood to include fresh inquiries into metal, stone, coal, terracotta roof tiles, and asphalt—all essential components of the city worker's daily life.","Leena Raj: Leena views the typical conception of a home as a constrained area of homogenised identities and broadens the idea of a person's home beyond the defined space of four walls. According to her, a home is made up of diverse lives brought about by the affectionate companionship or the incongruities of unfamiliarity in the relationships of its other residents. She searches for a place to call home in all directions and, as she shows her fondness for diverse microcosms, creates fantastical landscapes in which people coexist peacefully with the natural world.","Poorvesh Patel: Poorvesh's colour scheme serves as the protagonist in his works, which are amplified accounts of his personal adventures. Through his works, his emotional behaviour interacts with the current socio-political environment. He uses examples from his everyday life to help create a mental image, and compares it to his subconscious. That idea is omnipresent in his workflow. 'It is like seeing another life after a loss. It is like the phoenix having a rebirth every time.'","Sumana Som: Sumona engages in the practice of cartography, examining the aesthetics of visual representation while incorporating elements from Indian miniature painting traditions into her creations. She primarily uses textiles and manipulates the spatial relationships between her subjects to build layered narratives that unite the past and present in a single frame. Sumana addresses the intricate relationships between distance, boundary, ownership, encroachment, and power structures that permeate our daily lives through her endeavour."],
credit:"Hyperglot Review",
category:"Art Events",
subheading:"",
},
{id:'28' ,
url:["/eventimages/artofindia/artofindia (1).JPG"],
heading:"Art of India",
info:["The Art of India exhibition honours the country's rich and diverse history of visual arts and crafts. India has an honoured tradition of creating exceptional artistic works that go back to the very beginning of human civilisation, producing incredible sculptures, paintings, architecture as well as innovative art forms. Art has always had a profound impact on humanity and served as a means of creative expression that allowed for individual perception.","The exhibition aims to bring together artists and art enthusiasts by displaying their innovative artistic expressions and original ideas. The exhibition features a variety of artistic mediums, including mixed-media, photography, video, printing, sculpture, and ceramics. Through carefully planned shows that feature a variety of genres, one of the exhibition's objectives is to raise awareness of art throughout the Indian subcontinent."],
credit:"Hyperglot Review",
category:"Art Events",
subheading:"",
artists:[{id:'55',
"heading":"Dr. Tarana Khubchandani",
url:["/eventimages/artofindia/artofindia (4).JPG"],
info:["Dr. Tarana Khubchandani, the founder of Art & Soul gallery, is a trailblazer in the Indian art world. With a passion for aesthetic syncretism, she has curated exhibitions that span art historical timelines, genres, and materials. In her latest venture, Dr. Khubchandani collaborated with veteran artist Brinda Miller to curate the Art of India exhibition, an initiative aimed at making art more accessible and democratic.","The Art of India exhibition is a celebration of Indian art and pays tribute to the artists who laid the foundation of the art culture in India when it was still nascent. Dr. Khubchandani's curatorial note highlights the prominent Bengal Masters who have influenced Indian art, as well as the artists who have left indelible imprints on Indian art history. The exhibition features over 150 artworks by a diverse group of Indian artists, both newcomers and veteran artists.","The Art of India exhibition is a testament to Dr. Khubchandani's commitment to inclusion and diversity. The exhibition includes a mix of works from artists like Sujata Bajaj, whose works represent abstracted gestures, to Bose Krishnamachari's unrivalled Ghost series. The exhibition also includes film productions and sculptures, making it a multi-dimensional experience.","The Art of India exhibition is not just a showcase of Indian art, but a celebration of Indian culture. The exhibition is an opportunity for artists and art lovers from different genres to unite and appreciate the beauty of Indian art. Dr. Khubchandani's vision for the exhibition was to create an atmosphere of inclusion and diversity, where different mediums and artists of different genres could come together under one roof. The exhibition also includes workshops and programs, creating a holistic experience for visitors.","Dr. Tarana Khubchandani's Art of India exhibition is a reflection of her passion for Indian art and her commitment to inclusivity and diversity. The exhibition is a celebration of the rich history of Indian art and a tribute to the artists who have contributed to its development. Through this exhibition, Dr. Khubchandani has created a platform for artists and art lovers to unite and appreciate the beauty of Indian art."],
credit:"Art of India",
},{id:'50',
"heading":"Manas Naskar",
url:["/eventimages/gallerydotwalk/gallerydotwalk (4).JPG"],
info:["In order to better comprehend the changes in nature and the environment in his immediate surroundings, Manas Naskar experiments with different painting materials and techniques. He is attempting to revisit the current genre of paintings in a way that more closely resembles the romantics' ideology, which views both the calmness and the wrath of nature as beautiful. Manas strives to catch those ephemeral moments when a minute shift in the position of the sun produces a wonderful aura."],
credit:"Hyperglot Review",
},{id:'51',
"heading":"Midhun Gopi",
url:["/eventimages/gallerydotwalk/gallerydotwalk (5).JPG"],
info:["The journeys shown in Midhun's paintings seem to never end; they take the viewer through the wilderness, the cosmos, the interior landscapes of the mind, and the hardships of society. In certain instances, he weaves memories and feelings together so that they are lucid yet possess complexity. In his works, the sceneries and forms blend together and start to complement one another. The images evoke a sense of individual or community recollection mingled with forms."],
credit:"Hyperglot Review",
},{id:'52',
"heading":"Prerna Sharma",
url:["/eventimages/gallerydotwalk/gallerydotwalk (6).JPG"],
info:["Prerna uses fish as a metaphor for the psychological conflicts and feelings that people experience when they deal with others and with themselves. She believes that given that we can't see or hear a fish's agony or fear while they experience a range of emotions, suffering is frequently concealed on a person's face. The fish have tear ducts, but since their eyes are constantly wet, we cannot see them cry. Prerna still vividly recalls images of mass graves of dead people from the horrific tsunami that struck the coastline in 2014. Additionally, she utilises the analogy of fish to describe the trauma."],
credit:"Hyperglot Review",
},{id:'53',
"heading":"Sneh Mehra",
url:["/eventimages/gallerydotwalk/gallerydotwalk (7).JPG"],
info:["The works of Sneh Mehra are largely concerned with the land and environment and include other multidisciplinary aspects such as the evolution of the land, the environment and ecology, climate change, animal behaviour, etc. These are all staged in the landscape regime, which, throughout the history of art, has only ever been used to show natural surroundings such as mountains, rivers, sky, seascapes, etc. as the background of portraits. Her art is inspired by references that reflect her surroundings and the shards of chaotic growth and disintegration."],
credit:"Hyperglot Review",
},{id:'54',
"heading":"Tanaya Rao Raj",
url:["/eventimages/gallerydotwalk/gallerydotwalk (1).JPG"],
info:["Tanaya is passionate about upcycling and incorporates discarded and salvaged materials into her art practice. Her creations are the outward expressions of an innate need and need to employ (or repurpose) all manner of trash, including found things and materials. She uses paint and katran (or textile waste) to create varied sceneries and/or abstract forms that are influenced by nature in her most recent body of work. She considers every type of discarded material to be a reflection of herself, aiming to give each piece of art a unique purpose and identity."],
credit:"Hyperglot Review",
},
]
},
]

export default newseventsdata;