import "@/styles/Home.module.css";
import Head from "next/head";
import Navbar from "../components/navbar";
import Heroslider from "@/components/homecomponents/heroslider";
import Art from '../components/homecomponents/art';
import Literature from '../components/homecomponents/literature'
import Design from '../components/homecomponents/design'
import NewsnEvents from '../components/homecomponents/news'
import Download from '../components/homecomponents/indiaartfairspecial'
import Youtube from '../components/homecomponents/youtube'
import Footer from '../components/footer'
import dynamic from "next/dynamic";

// export const getStaticProps = async () => {
//   const [res1,res2,res4] = await Promise.all([
//   fetch("http://localhost:5000/api/posts"),
//   fetch("http://localhost:5000/api/bookreviews"),
//   fetch("http://localhost:5000/api/newss"),
// ]);
//   const [data1,data2,data4] = await Promise.all([
//     res1.json(),
//     res2.json(),
//     res4.json(),
//   ])

//   return {
//     props: {
//       data1,
//       data2,
//       data4,
//     },
//   };
// };

const Home = () => {

  return (
    <>
      <Head>
        <title>Hyperglot Review</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Navbar />
        <Heroslider />
        <Art />
        <Literature />
        {/* <Download /> */}
        <Youtube />
        <NewsnEvents />
        {/* <Design />*/}
        <Footer />
      </main>
    </>
  );
}

export default dynamic (() => Promise.resolve(Home), {ssr: false})